Add sections on DataLad and WebDAV access in download chapter
dandi/handbook pull request #139
Opened 2024-07-07 17:35 UTC by yarikoptic

Closes #133

2024-07-07 18:00 UTC, jwodder requested changes

2024-07-07 18:12 UTC, yarikoptic commented on docs/12_download.md
> +Dandiset releases are tagged with Git tags and a history of modifications is available at the time intervals of execution of the mirroring job.
if mentioning draft, I would like then to reorder...

```suggestion
The Git revision histories of each dataset reflect the Dandiset's draft state as of each execution of the mirroring job.
Published Dandiset versions are tagged with Git tags.
```

2024-07-07 18:13 UTC, yarikoptic commented on docs/12_download.md
> +Learn more about DataLad from its handbook at https://handbook.datalad.org/ .
ah, then we need to do similar above... will do

2024-07-09 18:16 UTC, yarikoptic commented
if no further comments / objections -- I will merge in few days.

2024-07-09 18:17 UTC, jwodder approved these changes

2024-07-09 18:21 UTC, merged